### PR TITLE
Added offset to angle measurement label

### PR DESCRIPTION
**Pull request by droidmonkey**
This makes it a little easier to read the angles and see the green line

### CODE REVIEW

**Comment by Simie** [comment]
Just tried it out, I'm not a fan of it sticking out this far, especially with multiple angles being shown at once. I think I'd like to leave it with the box sitting on the line for now.

Screenshot

**Comment by droidmonkey** [comment]
That's interesting, what resolution do you play at? At 1920x1080 it is just off the line w/o intersecting. I wonder if there is a way to move it a "resolution independent" distance. Sorry for the tab, still learning monodevelop's quirks

**Comment by Simie** [comment]
I usually have it set to Windowed mode 720p when working on the mod. Just tried it fullscreen, I don't notice much difference:

Screenshot

**Comment by droidmonkey** [comment]
ok thanks

**Pull request closed without merging**
