### PR TITLE
Adding support to ignore multiple implementations of NetTool

### PR DESCRIPTION
**Pull request by klyte45**
Hi!

I did a addition in the code to make it support other mods that have created tools with base as NetTool. It simply check for the exact implementation before trying to get from the cache.

This is needed to be compatible with my most recently [Upgrade Untouchable mod](https://steamcommunity.com/sharedfiles/filedetails/?id=2629141193). I hope you can update your mod soon at workshop.

Thanks!

Klyte

### CODE REVIEW

**Comment by Simie** [comment]
Thanks!

**Comment by klyte45** [comment]
Do you have a prevision about when the fix will be available in WS?

**Comment by Simie** [comment]
Just updated it :-)

**Comment by klyte45** [comment]
Thanks!

**Pull request merged**
